---
title: "Introduction"
# linktitle: "1. Introduction to RStudio and Images"
date: "2025-08-20"
class_date: "2025-08-20"
draft: true
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 1
type: docs
weight: 1
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Welcome slides

<a href="../../slides/00_Intro/00_Intro.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/00_Intro/00_Intro.html#1')
```

## R overview

<a href="../../slides/01a_R_Markdown/01a_RStudio.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01a_R_Markdown/01a_RStudio.html#1')
```

<a href="../../slides/01a_R_Markdown/01b_IntroRSlides.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01a_R_Markdown/01b_IntroRSlides.html#1')
```

<a href="../../slides/01a_R_Markdown/01c_Markdown.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01a_R_Markdown/01c_Markdown.html#1')
```

<a href="../../slides/01a_R_Markdown/01d_Mathjax.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01a_R_Markdown/01d_Mathjax.html#1')
```

<a href="../../slides/01a_R_Markdown/01e_Presentation.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01a_R_Markdown/01e_Presentation.html#1')
```

<a href="../../slides/01b_Graphics_dplyr/01b_dplyr.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01b_Graphics_dplyr/01b_dplyr.html#1')
```

<a href="../../slides/01b_Graphics_dplyr/01c_ggplot2.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/01b_Graphics_dplyr/01c_ggplot2.html#1')
```
