---
title: "scRNA-seq"
# linktitle: "1. Introduction to RStudio and Images"
date: "2026-03-23"
class_date: "2026-03-23"
draft: false
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 5
type: docs
weight: 5
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Single-cell RNA-seq

<a href="../../slides/10_single_cell/01_single_cell_xaringan.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/10_single_cell/01_single_cell_xaringan.html#1')
```

<a href="../../slides/10_single_cell/CellRanger.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/10_single_cell/CellRanger.html#1')
```

<a href="../../slides/10_single_cell/Seurat_slides_xaringan.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/10_single_cell/Seurat_slides_xaringan.html#1')
```

**Code:** Seurat tutorial [Seurat_code.Rmd](../../slides/10_single_cell/Seurat_code.Rmd), [Seurat_code.html](../../slides/10_single_cell/Seurat_code)

<a href="../../slides/10_single_cell/02_tSNE_xaringan.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/10_single_cell/02_tSNE_xaringan.html#1')
```

<a href="../../slides/10_single_cell/03_UMAP.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/10_single_cell/03_UMAP.html#1')
```

<a href="../../slides/10_single_cell/Integration_batch.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/10_single_cell/Integration_batch.html#1')
```


[How PCA projection and cell label transfer work in Seurat](https://crazyhottommy.github.io/single-cell-RNAseq-PCA-CCA-cell-annotation/how-seurat-pca-label-transfer.html)

[How CCA alignment and cell label transfer work in Seurat](https://crazyhottommy.github.io/single-cell-RNAseq-PCA-CCA-cell-annotation/how-seurat-cca-label-transfer.html)

