---
title: "Code 1"
date: "2025-01-27"
due_date: "2025-01-27"
due_time: "11:59 PM"
draft: false
menu:
  assignment:
    parent: Code
    weight: 2
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: false
editor_options: 
  chunk_output_type: console
---

<!-- # In-class, [deep-learning-with-r-notebooks](https://github.com/jjallaire/deep-learning-with-r-notebooks) -->

<!-- - `2.1-a-first-look-at-a-neural-network.Rmd` - MNIST, feedforward DNN -->

# Self-study

Neural network introduction, main ingredients, activation function, gradient descent, learning rate, ReLU, train-test-validation, prediction

- Follow installation instructions in [installation_code.R](../../slides/code/installation_code.R). Note we are installing the [keras3](https://keras3.posit.co/) package.
- Download [01-main-ingredients_code.Rmd](../../slides/code/01-main-ingredients_code.Rmd). Modified from [dl-keras-tf](https://github.com/rstudio-conf-2020/dl-keras-tf).
- Download [01-main-ingredients_images.zip](../../slides/code/01-main-ingredients_images.zip). Extract the `images` folder in the same directory as the `01-main-ingredients_code.Rmd` file.
- Read and run the code in the `01-main-ingredients_code.Rmd` file. Consult ChatGPT in case of errors.
- Answer questions in the code chunks currently set to `eval=FALSE`.
- Knit the document into an HTML format and submit the knitted document.
